traduït vscode.cpp.i18n.json
aitor-gomila/vscode-language-pack-ca pull request #2
Opened 2023-08-01 21:27 UTC by pocsenderi

però no tinc ni idea si ho he fet bé o què...

2023-08-02 11:03 UTC, aitor-gomila commented
Hola poc! Gràcies per la teva contribució. He arrenjat qualqunes coses a https://github.com/pocsenderi/vscode-language-pack-ca/pulls/2

2023-08-02 11:05 UTC, aitor-gomila requested changes
Hola poc! Gràcies per la teva contribució. He arrenjat qualqunes coses a https://github.com/pocsenderi/vscode-language-pack-ca/pull/2.

2023-08-02 12:01 UTC, pocsenderi commented
No me'n vaig sortir de canviar el readme i posar-lo al mateix commit i ho vaig deixar córrer. A veure si la propera vegada ho faig millor.

D'altra banda, ja he instal·lat el paquet d'idioma i he trobat cosetes. Ja te les faré arribar.

Gràcies.
------- Original Message -------
El dimecres, 2 de agost 2023 a les 13:05, aitor-gomila ***@***.***> va escriure:

> @aitor-gomila requested changes on this pull request.
>
> [pocsenderi#2](https://github.com/pocsenderi/vscode-language-pack-ca/pull/2)
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/aitor-gomila/vscode-language-pack-ca/pull/2#pullrequestreview-1558763465), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BBVE7BBGVO52GXLBYWFU6M3XTIX7JANCNFSM6AAAAAA3ALFLTI).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-03 06:43 UTC, merged

2023-08-05 07:04 UTC, GreenBeetleStore commented
Correccions del menú : 

File = Fitxer
EEdita = Editar
Go = Anar a
Run = Executar